const menu = [
  {
    id: 1,
    title: 'Daiquiri Frozen de frutilla',
    category: 'dulces',
    price: 500,
    img: './images/item-1.jpeg',
    desc: `Ron Dorado, Frutillas, Azúcar`,
    nivel: 1,
  },
  {
    id: 2,
    title: 'Sex on the Beach',
    category: 'dulces',
    price: 400,
    img: './images/item-2.jpeg',
    desc: `Vodka, Licor de Durazno, Jugo de Naranja, Jugo de Arándanos, Granadina`,
    nivel: 2,
  },
  {
    id: 3,
    title: 'Ancho de Espadas (by Agus Ottaviano)',
    category: 'dulces',
    price: 600,
    img: './images/item-2.jpeg',
    desc: `Whisky, Licor de Chocolate, Licor de Chocolate blanco, Licor de Coco, Café, Helado
    de Vainilla`,
    nivel: 2,
  },
  {
    id: 4,
    title: 'Parque de Diversiones (by Jacqueline Fierro)',
    category: 'dulces',
    price: 550,
    img: './images/item-2.jpeg',
    desc: `Vodka, Licor de Chocolate blanco, Crema de Leche, Mermelada de Frutilla, Almibar
    de Coco`,
    nivel: 2,
  },
  {
    id: 5,
    title: 'Mono Rabioso (by Agus Ottaviano)',
    category: 'dulces',
    price: 600,
    img: './images/item-2.jpeg',
    desc: `Vodka de Palito de la Selva, Aperol,Licor de Frutilla, Licor de Chocolate blanco, Mix
    ̈Rabioso ̈ (el mix está hecho con bananas, leche condensada y zumo de limón)`,
    nivel: 4,
  },
  {
    id: 6,
    title: 'Sex on the Vinilo ́s Beach',
    category: 'dulces',
    price: 450,
    img: './images/item-2.jpeg',
    desc: `Vodka Citrus, Licor de Coco, Jugo de Naranja, Jugo de Arándanos, Granadina`,
    nivel: 2,
  },
  {
    id: 7,
    title: 'Caipirinha de Frutos Rojos',
    category: 'dulces',
    price: 500,
    img: './images/item-2.jpeg',
    desc: `Cachaza, Limas, Frutos rojos, Azúcar`,
    nivel: 3,
  },
  {
    id: 8,
    title: 'Caipiroska de Frutos Rojos',
    category: 'dulces',
    price: 500,
    img: './images/item-2.jpeg',
    desc: `Vodka, Limas, Frutos Rojos, Azúcar`,
    nivel: 3,
  },
  {
    id: 9,
    title: 'Mojito de Frutos Rojos (XL)',
    category: 'dulces',
    price: 650,
    img: './images/item-2.jpeg',
    desc: `Ron Blanco, Limas, Menta, Azúcar, Soda`,
    nivel: 3,
  },
  {
    id: 10,
    title: 'Soul of Cocoffe (by Agus Ottaviano)',
    category: 'dulces',
    price: 600,
    img: './images/item-2.jpeg',
    desc: `Ron Blanco, Licor de Coco, Almíbar de Vainilla, Cafe`,
    nivel: 4,
  },

  {
    id: 11,
    title: 'Negroni Argento',
    category: 'amargos',
    price: 500,
    img: './images/item-2.jpeg',
    desc: `Gin Príncipe de los Apóstoles, Bitter Verbena, Vermouth Lunfa`,
    nivel: 4,
  },
  {
    id: 12,
    title: 'Vermouth (Lunfa, La Fuerza o Mala María)',
    category: 'amargos',
    price: 500,
    img: './images/item-2.jpeg',
    desc: `Vermouth Blanco o Rosso, Soda`,
    nivel: 2,
  },
  {
    id: 13,
    title: 'Campari Tonic',
    category: 'amargos',
    price: 450,
    img: './images/item-2.jpeg',
    desc: `Campari, Agua Tónica`,
    nivel: 2,
  },
  {
    id: 14,
    title: 'Garibaldi (Chico)',
    category: 'amargos',
    price: 320,
    img: './images/item-2.jpeg',
    desc: ``,
    nivel: 0,
  },
  {
    id: 15,
    title: 'Garibaldi (XL)',
    category: 'amargos',
    price: 520,
    img: './images/item-2.jpeg',
    desc: `Campari, Jugo de Naranja`,
    nivel: 2,
  },
  {
    id: 16,
    title: 'Fernet (Chico)',
    category: 'amargos',
    price: 320,
    img: './images/item-2.jpeg',
    desc: ``,
    nivel: 0,
  },
  {
    id: 17,
    title: 'Fernet (XL)',
    category: 'amargos',
    price: 520,
    img: './images/item-2.jpeg',
    desc: `Fernet, Coca Cola`,
    nivel: 2,
  },
  {
    id: 18,
    title: 'Fermelo (Chico)',
    category: 'amargos',
    price: 320,
    img: './images/item-2.jpeg',
    desc: ``,
    nivel: 0,
  },
  {
    id: 19,
    title: 'Fermelo (XL)',
    category: 'amargos',
    price: 520,
    img: './images/item-2.jpeg',
    desc: `Fernet, Schweppes de pomelo`,
    nivel: 2,
  },
  {
    id: 20,
    title: 'Palo Borracho (by Agus Ottaviano)',
    category: 'amargos',
    price: 550,
    img: './images/item-2.jpeg',
    desc: `Gin, Pineral, Campari, Almíbar Simple, Jugo de Pomelo, Soda`,
    nivel: 3,
  },
  {
    id: 21,
    title: 'Italian Job',
    category: 'amargos',
    price: 400,
    img: './images/item-2.jpeg',
    desc: `Licor de Café, Amaretto, Café, Crema de Leche`,
    nivel: 2,
  },
  {
    id: 22,
    title: 'Aperol Spritz',
    category: 'amargos',
    price: 550,
    img: './images/item-2.jpeg',
    desc: `Aperol, Champagne, Soda`,
    nivel: 2,
  },
  {
    id: 23,
    title: 'Wesley (London Dry)',
    category: 'amargos',
    price: 800,
    img: './images/item-2.jpeg',
    desc: `Wesley nos trae desde Bariloche dos variedades de Gin: el clásico London
    Dry (con 43% de graduación alcohólica) en el que sobresale el aroma a
    enebro y otro London Dry (también con 43% de graduación alcohólica)
    infusionado con frambuesas y cassis. Elegí el que más te guste.`,
    nivel: 0,
  },
  {
    id: 43,
    title: 'Restinga (London Dry)',
    category: 'amargos',
    price: 600,
    img: './images/item-2.jpeg',
    desc: `Este Gin marplatense es un London Dry con una pequeña vuelta de tuerca,
    en el primer sorbo vas a notar el enebro, el cardamomo y el laurel (entre
    otros ingredientes) que pueden asemejarse a un leve dulzor, pero al final te
    vas a encontrar con el amargor y el trago seco, típico de un London Dry.`,
    nivel: 0,
  },
  {
    id: 24,
    title: 'Poción Multijugos (By Agus Ottaviano)',
    category: 'balanceados',
    price: 450,
    img: './images/item-2.jpeg',
    desc: `Gancia, Almíbar de Remolacha, Zumo de limón, Sandía`,
    nivel: 1,
  },
  {
    id: 25,
    title: 'Caipirinha',
    category: 'balanceados',
    price: 450,
    img: './images/item-2.jpeg',
    desc: `Cachaza, Limas, Azúcar`,
    nivel: 3,
  },
  {
    id: 26,
    title: 'Caipiroska',
    category: 'balanceados',
    price: 450,
    img: './images/item-2.jpeg',
    desc: `Vodka, Limas, Azúcar`,
    nivel: 3,
  },
  {
    id: 27,
    title: 'Caipirinha de Maracuyá',
    category: 'balanceados',
    price: 500,
    img: './images/item-2.jpeg',
    desc: `Cachaza, Limas, Maracuyá, Azúcar`,
    nivel: 3,
  },
  {
    id: 28,
    title: 'Caipiroska de Maracuyá',
    category: 'balanceados',
    price: 500,
    img: './images/item-2.jpeg',
    desc: `Vodka, Limas, MAracuyá, Azúcar`,
    nivel: 3,
  },
  {
    id: 29,
    title: 'Mojito (XL)',
    category: 'balanceados',
    price: 600,
    img: './images/item-2.jpeg',
    desc: `Ron Blanco, Limas, Menta, Azúcar, Soda`,
    nivel: 3,
  },
  {
    id: 30,
    title: 'Mojito de Maracuyá (XL)',
    category: 'balanceados',
    price: 650,
    img: './images/item-2.jpeg',
    desc: `Ron Blanco, Limas, Maracuyá, Menta, Azúcar`,
    nivel: 3,
  },
  {
    id: 31,
    title: 'Té de Cazador',
    category: 'balanceados',
    price: 550,
    img: './images/item-2.jpeg',
    desc: `Jägermeister, Té negro, Mermelada de Naranja, Zumo de Limon, Azúcar`,
    nivel: 4,
  },
  {
    id: 32,
    title: 'Better Call Saúl (by Agus Ottaviano)',
    category: 'balanceados',
    price: 470,
    img: './images/item-2.jpeg',
    desc: `Tequila, Campari, Miel, Almíbar de Jengibre, Zumo de Limón, Jugo de Pomelo`,
    nivel: 4,
  },
  {
    id: 33,
    title: 'AstraZeneca (by Agus Ottaviano)',
    category: 'balanceados',
    price: 600,
    img: './images/item-2.jpeg',
    desc: `Tequila, Gancia, Licor de Kiwi, Licor de Menta, Almíbar especial de Palta,
    Zumo de Limón, Soda (2da Dosis: Jeringa con Tequila)`,
    nivel: 5,
  },
  {
    id: 34,
    title: 'Cynar Julep (XL)',
    category: 'balanceados',
    price: 650,
    img: './images/item-2.jpeg',
    desc: `Cynar, Limas, Menta, Azúcar, Agua Tónica de Pomelo`,
    nivel: 3,
  },
  {
    id: 35,
    title: 'Cuba Libre (Chico)',
    category: 'balanceados',
    price: 350,
    img: './images/item-2.jpeg',
    desc: ``,
    nivel: 0,
  },
  {
    id: 36,
    title: 'Cuba Libre (XL)',
    category: 'balanceados',
    price: 650,
    img: './images/item-2.jpeg',
    desc: `Ron Dorado, Zumo de Limón, Coca Cola`,
    nivel: 2,
  },
  {
    id: 37,
    title: 'Gancia (Chico)',
    category: 'balanceados',
    price: 320,
    img: './images/item-2.jpeg',
    desc: ``,
    nivel: 0,
  },
  {
    id: 38,
    title: 'Gancia (XL)',
    category: 'balanceados',
    price: 520,
    img: './images/item-2.jpeg',
    desc: `Gancia, Sprite, Limón`,
    nivel: 1,
  },
  {
    id: 39,
    title: 'Gancia Batido',
    category: 'Cítricos',
    price: 400,
    img: './images/item-2.jpeg',
    desc: `Gancia, Zumo de Limón, Almíbar Simple`,
    nivel: 0,
  },
  {
    id: 40,
    title: 'Fiona (by Jacqueline Fierro)',
    category: 'Cítricos',
    price: 550,
    img: './images/item-2.jpeg',
    desc: `Gin, Zumo de Limón, Almíbar Simple, Jengibre, Menta`,
    nivel: 0,
  },
  {
    id: 41,
    title: 'Cítrico',
    category: 'sin alcohol',
    price: 420,
    img: './images/item-2.jpeg',
    desc: `Terma Citrus, Zumo de limón, Almíbar de Jengibre, Agua Tónica`,
    nivel: 0,
  },
  {
    id: 42,
    title: 'Dulce',
    category: 'sin alcohol',
    price: 420,
    img: './images/item-2.jpeg',
    desc: `Pulpa de Frutilla, Jugo de Arándanos, Jugo de Naranja, Almíbar de Pomelo -
    Naranja - Anís, Agua Tónica de Pomelo`,
    nivel: 0,
  },
];
export default menu;
